name: gh-teacher
version: git
summary: gh-teacher helps teachers manage courses and exams that use GitHub.
description: >
  gh-teacher helps teachers manage courses and exams that use GitHub.

confinement: strict

parts:
  gh-tools:
    plugin: python
    python-version: python3
    source: .
    requirements: requirements.txt
    stage-packages:
      - git
      - ssh
  locales-launch:
    # Remote part to get proper locale support.
    #   More info: https://forum.snapcraft.io/t/the-locales-launch-remote-part/8729

apps:
  gh-tools:
    command: locales-launch $SNAP/usr/bin/python3 $SNAP/bin/gh-tools
    plugs:
      - home
      - network
      - ssh-keys
