name: ghtt
title: Github Teacher Tools
version: git
summary: ghtt helps teachers manage courses and exams that use GitHub.
description: |
  ghtt helps teachers manage courses and exams that use GitHub.

base: core18
confinement: strict

apps:
  ghtt:
    command: bin/ghtt
    # https://forum.snapcraft.io/t/solved-utf-8-not-supported-in-snap/5994/5
    # https://forum.snapcraft.io/t/the-locales-launch-remote-part/8729
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - home
      - network
      - ssh-keys
      - removable-media

parts:
  gh-teacher-tools:
    plugin: python
    python-version: python3
    source: .
    requirements: 
      - requirements.txt
    stage-packages:
      - git
      - ssh

plugs:
  gitconfig:
    interface: personal-files
    read:
      - $HOME/.gitconfig         # the old location
      - $HOME/.config/git/config # the new location (people could change it via XDG_CONFIG_HOME and that isn't supported by snapd yet)
